# Generated by Django 4.2.1 on 2023-05-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transactiontype_alter_expense_category_and_more'),
        ('tracker', '0004_alter_expense_category'),
    ]

    operations = [
    ]
